/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'YPierru' at '23/02/16 10:08' with Gradle 2.6
 *
 * @author YPierru, @date 23/02/16 10:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
